version: '3'

services:
  db:
    image: mysql:5.7
  ports:
    3306: 3306
  environment:
    - MYSQL_DATABASE=${DB_NAME}
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

    volumes:
      - ${DB_CONF_DIR}:/var/lib/mysql:cached
      - ${DB_CONF_DIR}:/etc/mysql/conf.d:cached

  swagger:
    image: "swaggerapi/swagger-ui:latest"