version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./database/conf/:/etc/mysql/conf.d:cached
      - ./database/data/:/var/lib/mysql:cached
    env_file: .env

  swagger:
    image: "swaggerapi/swagger-ui:latest"
    volumes:
      - ./swagger:/usr/share/nginx/html/dist:cached
    ports:
      - "8081:8080"
    environment:
      - API_URL=dist/swagger.json